### ISSUE TITLE
As a user , I want to have an account

### ISSUE THREAD

**Issue by seaiam** [hakimsheriff/SOEN341Project#11]
**Description:**
Users need to be able to have an account on pigeon post

**Steps:**
-register the user
-allow the user to log in

**Priority:**
High

**Comment by Ahmad-ConU** [comment]
I am able to create and account and the account information is stored for when I log in.

**Comment by hakimsheriff** [comment]
Acceptance test for this feature:

- [x] Load website
- [x] Click the "Sign Up" button on the top right
- [x] Enter an invalid username
- [x] Enter an invalid password
- [x] Verify that you receive an error message preventing an account from being created
- [x] Enter an invalid username
- [x] Enter a valid password
- [x] Verify that you receive an error message preventing an account from being created
- [x] Enter a valid username
- [x] Enter an invalid password
- [x] Verify that you receive an error message preventing an account from being created
- [x] Enter a valid username
- [x] Enter a valid password
- [x] Verify that you are redirected to main page
- [x] On the top right, click "login"
- [x] Enter a false username and password
- [x] Verify that you receive an error message
- [x] Enter your real, newly created, username and password
- [x] Verify that you are redirected to the main feed
- [x] At the top of the feed, the page should now read "Welcome" followed by your username

This was tested and all aspects are functioning as expected.
