### ISSUE TITLE
Task: Fix Travis-CI Integration

### ISSUE THREAD

**Issue by hakimsheriff** [hakimsheriff/SOEN341Project#25]
Description:
Fix travis-ci integration

Steps:
Fix requirements.txt and dependecy requirements that are causing travis-ci issues

Priority:
Very High

**Comment by Lucas-ConU** [comment]
![traviserror](https://user-images.githubusercontent.com/77515701/109257846-01f59100-77c7-11eb-91f3-efb614fc679e.JPG)
