### ISSUE TITLE
As a user, I would like to receive and send notifications from/to another user

### ISSUE THREAD

**Issue by Ahmad-ConU** [hakimsheriff/SOEN341Project#4]
**Description:** 
Users should be able to receive a notification when someone follows them or likes their picture
**Steps:**
-Send notification to user when someone follows them or likes their picture
**Priority:**
Low

**Comment by timotei1** [comment]
Description: 
User is notified every time another user follows them or interacts with their pictures.

Difficulty:
6

Priority:
LOW - Not a core feature, but a good addition to the user experience.

**Comment by seaiam** [comment]
We have decided to not implement this feature.
