### ISSUE TITLE
As a user , i would like to like another user's post

### ISSUE THREAD

**Issue by seaiam** [hakimsheriff/SOEN341Project#40]
**Description:**
Users should be able tolike and unlike another user's posts
**Steps:**
-make sure user is logged in
- if user logged in , allow him to add a like to post
- if user already like post , allow user to unlike
**Priority:**
medium

**Comment by hakimsheriff** [comment]
Acceptance test for this feature

- [ ] Log in to a user account
- [ ] Find the post you would like to "like"
- [ ] Press on the "like" button
- [ ] Verify that the like counter has incremented
- [ ] Verify that the "like" button now reads "unlike"
- [ ] Press the "unlike" button
- [ ] Verify that the like counter has decremented
- [ ] Verify that the "unlike" button now read "like"
