### ISSUE TITLE
Task: let user register (create account)

### ISSUE THREAD

**Issue by Lucas-ConU** [hakimsheriff/SOEN341Project#5]
**Description:** 
Users should be able to register
**Steps:**
-ask user for their email , username and password
-make sure the password is valid
-store user's information
**Priority:**
High , other core features rely on this to be implemented

**Comment by timotei1** [comment]
Description:
User creates a username and a password combination that will be used to login into his/her account.

Difficulty:
4

Priority:
HIGH
